"use client";
import React from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { motion } from 'framer-motion';

export default function TermsOfService() {
    return (
        <main className="min-h-screen bg-background text-white">
            <Navbar />

            <div className="container mx-auto px-6 pt-32 pb-20">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="max-w-4xl mx-auto"
                >
                    <h1 className="text-4xl md:text-6xl font-bold mb-8">Terms of <span className="text-gradient">Service</span></h1>

                    <div className="prose prose-invert max-w-none space-y-8 text-gray-300">
                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
                            <p>By accessing and using Promptova AI, you agree to be bound by these Terms of Service and all applicable laws and regulations.</p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
                            <p>Promptova AI provides artificial intelligence-powered tools for image generation, emoji creation, resume analysis, and storytelling. We provide "Unlimited" access subject to our fair use policy.</p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">3. User Conduct</h2>
                            <p>Users agree not to use the service for any unlawful purposes or to generate content that is harmful, abusive, or violates third-party rights.</p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">4. Intellectual Property</h2>
                            <p>The content generated by users through Promptova AI is owned by the user, while the underlying technology and platform remain the property of Promptova AI.</p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">5. Disclaimer</h2>
                            <p>The service is provided "as is" without warranties of any kind. We do not guarantee the accuracy or reliability of AI-generated content.</p>
                        </section>

                        <p className="text-sm text-gray-500 mt-12">Last Updated: March 2026</p>
                    </div>
                </motion.div>
            </div>

            <Footer />
        </main>
    );
}
